Badly placed ()'s.
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 61, in run
    self.optimize()
  File "inference/bucket_renormalization.py", line 51, in optimize
    new_mb_projector = self._get_svd_projector(marginal_factor, mb_var)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 323, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 466, in <module>
    Z = BucketRenormalization(seattle, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 466, in <module>
    Z = BucketRenormalization(seattle, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 466, in <module>
    Z = BucketRenormalization(seattle, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
