Badly placed ()'s.
Traceback (most recent call last):
  File "/groups/chertkov/rabrams/bucket-renormalization/tools.py", line 266, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "/groups/chertkov/rabrams/bucket-renormalization/tools.py", line 266, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "/groups/chertkov/rabrams/bucket-renormalization/tools.py", line 266, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "/groups/chertkov/rabrams/bucket-renormalization/tools.py", line 266, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "/groups/chertkov/rabrams/bucket-renormalization/tools.py", line 266, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "/groups/chertkov/rabrams/bucket-renormalization/tools.py", line 266, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "/groups/chertkov/rabrams/bucket-renormalization/tools.py", line 266, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "/groups/chertkov/rabrams/bucket-renormalization/tools.py", line 266, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "/groups/chertkov/rabrams/bucket-renormalization/tools.py", line 266, in compute_partition_functionsParallel
    Z_copy = BucketRenormalization(model_copy, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
Traceback (most recent call last):
  File "marginalization.py", line 84, in <module>
    compute_marginals(seattle, init_inf, (BETA, MU, TAU))
  File "/groups/chertkov/rabrams/bucket-renormalization/tools.py", line 185, in compute_marginals
    Z = BucketRenormalization(seattle, ibound=10).run(max_iter=1)
  File "inference/bucket_renormalization.py", line 14, in __init__
    self.initialize_projectors()
  File "inference/bucket_renormalization.py", line 25, in initialize_projectors
    replicated_projector = self._get_svd_projector(fac, rvar)
  File "inference/bucket_renormalization.py", line 82, in _get_svd_projector
    raise ValueError()
ValueError
